### ISSUE TITLE
SDK initialization fails if default browser is not set on the device.

### ISSUE THREAD

**Issue by saarikiv** [Tealium/tealium-android#63] opened 2019-04-08 08:52 UTC
Scenario:
-User has set Crome as the default browser (or any  other browser).
-User removes the Crome from the device, after which there is no default browser set.
-User starts an application with Tealium SDK
-SDK starts to load JavaScript to webview
-Application crashes

The SDK should check that are there browser support available for the webview and load JS only if there is - or - handle the exception so that the whole application does not crash.

It's better to loose one user tracking information than block the user from using the application.

**Comment by jameskeith** [comment] 2019-04-08 08:55
Thanks for flagging this @saarikiv 

I'll take a look at replicating it locally and see what we can do about failing gracefully for this scenario. Will get back to you once we've been able to take a look.

Out of curiosity, which version of our SDK are you using? and which version of Android?

**Comment by saarikiv** [comment] 2019-04-09 06:15
Sorry for not adding the information up front...
The device was Samsung Galaxy S9+ with Android 8.0.0 and the version of SDK was 5.5.4.

**Comment by jameskeith** [comment] 2019-04-09 17:16
@saarikiv - are you able to replicate this on the Emulator at all? I have tried building a sample app on an emulator for API level 26 (Android 8.0) using our SDK v5.5.4 but I cannot make this crash.
 - I would have expected the System WebView to have covered this kind of issue anyhow.

Incidentally, I am only able to "disable" Chrome rather than "uninstall" it completely; perhaps that's something specific to the Samsung phones. I'll try and find a Samsung device to confirm.

**Comment by saarikiv** [comment] 2019-04-10 15:05
We have not tested with emulator. My guess is that this is Samsung specific problem. When I tried to remove Crome from Huawei device, I could not. Also when I removed Firefox, which was my default browser, the system assigned default browser to Crome automatically.

**Comment by craigrouse** [comment] 2019-04-10 16:15
@saarikiv I just tried this on my Samsung device. If I _disable_ Chrome, which is the only option, it falls back to Android System Webview and there is no crash. If I re-enable Chrome, the system automatically reverts the webview back to Chrome, and there is no crash.

The only way you can actually remove Chrome (or the system webview, for that matter), is to root your device and forcibly remove the apps, which would mean many apps would fail to work correctly, and would certainly not be advisable. 

I have a stock Samsung S8+ with Android 8.

Are you seeing this issue on a device you own, or has it been reported by one of your end users?

The WebView APIs are pretty standard, and there isn't anywhere I know of that it tells you in the documentation to check if the system contains a webview; since it's a standard part of every stock Android firmware, there should not be any cases where it is impossible to instantiate a webview instance.

Do you have any further thoughts on this? Are you seeing the issue for just a single user, or several users?

Thanks,

Craig.

**Comment by saarikiv** [comment] 2019-04-11 10:02
This was a single device, with which we have seen the issue.

Our tester also "disabled" crome (can't be removed).

The tester did a factory reset to the device and repeated the scenario. It did not reproduce. Must have been some specific configuration issue with the device. The default browser was not set.
Like you said, in your case the default browser was set to the falback wbe view.

Maybe this is not worth while to investigate further.

**Comment by craigrouse** [comment] 2019-04-11 13:03
@saarikiv we will close this issue for now, since we can't reproduce it on any devices. If you come across it again, please don't hesitate to reopen the issue. Thanks for taking the time to report the issue.

**Closed by craigrouse** 2019-04-11 13:03 UTC
