### ISSUE TITLE
tealiumVersion = '5.2.0' SQLiteDatabaseCorruptException: database disk image is malformed

### ISSUE THREAD

**Issue by OmkarAmberkar** [Tealium/tealium-android#26] opened 2017-06-20 18:33 UTC
```Caused by android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:853)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:974)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
       at com.tealium.internal.data.DispatchStore.a(Unknown Source)
       at com.tealium.internal.data.DispatchStore.update(Unknown Source)
       at com.tealium.internal.data.DispatchStore.<init>(Unknown Source)
       at com.tealium.library.c.<init>(Unknown Source)
       at com.tealium.library.c.<init>(Unknown Source)
       at com.tealium.library.Tealium.createInstance(Unknown Source)
       at co.bytemark.analytics.TealiumPlatformAnalytics.initializeAnalyticsPlatform(TealiumPlatformAnalytics.java:120)```

**Comment by craigrouse** [comment] 2017-06-20 19:33
@omkaramberkar we haven't seen this issue before. From a quick look online, I've found that this may be caused by an unsupported character being stored in the sqlite db, which is what we use internally for storing dispatch data when the device doesn't have a good connection. Are you passing any non-standard characters in any of your tracking calls to Tealium? How often is this issue happening, and can you reproduce it? We will take a look at our code and see if this is something we can protect against in future.

**Comment by craigrouse** [comment] 2017-08-15 16:05
@OmkarAmberkar any updates on my question above? We have not been able to reproduce this issue so far.

**Comment by craigrouse** [comment] 2018-03-07 11:54
@OmkarAmberkar We have released a fix for a separate database-related issue that may also address this problem. I will close this issue for now. Please update to SDK version 5.4.1 and let us know if you see this issue after updating.

**Closed by craigrouse** 2018-03-07 11:54 UTC
