### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by StephaneBg** [Tealium/tealium-android#71] opened 2019-12-18 12:43 UTC
Hello,
since last version, an issue with obfuscation is encountered. Here is the logs:
```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tealium/library/A;
       at com.tealium.library.Tealium$Config.create(Tealium.java:1)
       at com.xxx.androidapp.pulsar.PulsarManager.initTagManager(PulsarManager.java:142)
       at com.xxx.androidapp.activities.AbstractActivity.onAppConfigLoaded(AbstractActivity.java:896)
       at com.xxx.androidapp.activities.AbstractActivity.onAppConfigLoaded(AbstractActivity.java:870)
       at com.xxx.androidapp.activities.xxxListActivity$1.onJsonResponse(xxxListActivity.java:146)
       at com.xxx.androidapp.activities.xxxListActivity$1.onJsonResponse(xxxListActivity.java:139)
       at com.xxx.androidapp.ws.JsonCallback$1.run(JsonCallback.java:69)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by java.lang.ClassNotFoundException: Didn't find class "com.tealium.library.A"
```
Documentation about proguard rules cannot be found on your site nor sample examples.

Can you provide any useful information about the obfuscation rules please?

**Comment by tamayok** [comment] 2019-12-18 18:39
@StephaneBg Just took a look at the Tealium Library aar file. All classes should be available. Here's the proguard rules within the Tealium Library:
```
-keep public class com.tealium.library.* {
    public protected *;
}
```
We can add this and more information around proguard rules into documentation.

**Comment by StephaneBg** [comment] 2019-12-19 07:18
Hello,
thanks for the fast reply. Unfortunately it didn't work.
Please advise.

**Comment by StephaneBg** [comment] 2019-12-19 08:50
I think proguard rules should be embedded into the library so that consumers don't have to worry about it.

**Comment by tamayok** [comment] 2019-12-23 16:07
@StephaneBg Thanks for you patience. We'll have a release ready soon with the proguard-rules embedded.

**Comment by tamayok** [comment] 2019-12-26 20:19
@StephaneBg The latest release contains the embedded proguard-rules. Please let us know if any issues arise. Thanks.

**Comment by StephaneBg** [comment] 2020-01-10 14:14
Hello,
thanks for the fast update. Unfortunately, the same issue still occurs.

**Comment by tamayok** [comment] 2020-01-10 17:35
@StephaneBg Some last checks to try: Clear your caches, clean project and/or double check your project build path.

If that doesn't work, please reach out to the Tealium support team at support@tealium.com so we can take a better look at your issue.

**Comment by mkotyk-godaddy** [comment] 2020-02-06 14:31
@StephaneBg I was encountering the same issue.  It turned out to be this caused by the Tealium classes being put into the classes2.dex file instead of the primary one.  See 
https://developer.android.com/studio/build/multidex#keep

I didn't have any luck using the `multiDexKeepProguard` as suggest.  Instead I solved it by ensuring I didn't use any Tealium api calls in my `onCreate` Application method.

**Comment by mkotyk-godaddy** [comment] 2020-02-06 20:08
Well my previous answer turned out not to solve my problem.  In a simple test app, the tealium library worked fine as-is.  As soon as I brought it into our product, it couldn't resolve `com.tealium.library.A`

What eventually worked for me was this.
- I extracted the `tealium-5.6.2.aar` archive. 
- I then opened `classes.jar` with [Recaf](https://github.com/Col-E/Recaf)
- I changed the 4 argument constructor for `Tealium.Config` to be `public`
- I changed the method 'a' in 'b.class' to also be public
- I saved the modified `classes.jar`
- I re-zipped up the .aar file
- I put this in my $project/libs directory and included it in my gradle build
- Then I was able to extend the `Tealium.Config` class (as it is abstract) with my own class, calling the 4 arg constructor.
- After that, things worked fine

@tamayok There are indeed issues with this SDK when used in a large app.  I think the build obfuscation step might be breaking the byte code, but only in certain cases.

**Comment by tamayok** [comment] 2020-02-13 15:43
@StephaneBg @mkotyk-godaddy Please take a look at our latest release. This should have resolved the proguard issue. Let us know if you continue to come across the same issue.

**Comment by mkotyk-godaddy** [comment] 2020-02-13 16:03
Can confirm 5.7.0 is working for us.  🎉

**Comment by tamayok** [comment] 2020-02-19 21:53
@mkotyk-godaddy @StephaneBg Closing this issue. If you experience additional problems with proguard, please let us know.

**Closed by tamayok** 2020-02-19 21:53 UTC
